sudo: required
services:
  - docker

before_install:
  docker build -t troy/docker-react -f Dockerfile.dev .

script:
  docker run -e CI=true troy/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-475987840838"
  bucker_path: "docker-react"
  access_key_id:
    secure: 
  on:
    branch: master
  
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  
  secret_access_key:
    secure: "$AWS_SECRET_KEY"